name: newsapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  # firebase_messaging: ^14.6.6
  # shared_preferences: ^2.2.0
  # firebase_core

  # firebase_auth
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.3
  firebase_core: ^2.23.0
  shared_preferences: ^2.2.0
  firebase_messaging: ^14.7.5
  get: 4.6.6
  http: ^1.1.0
  equatable: ^2.0.3
  flutter_svg: ^1.1.4
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.13

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/images/
  - assets/icons/

fonts:
  - family: SF-Pro-Display
    fonts:
      - asset: assets/fonts/SF-Pro-Display-Regular.otf
      - asset: assets/fonts/SF-Pro-Display-Semibold.otf
        weight: 600
      - asset: assets/fonts/SF-Pro-Display-Bold.otf
        weight: 700
