// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXwXlUYS9HDopAwSJfXoqpRB2N5OooAyM',
    appId: '1:1048741213886:web:d32b72e8017bb13f4350ef',
    messagingSenderId: '1048741213886',
    projectId: 'login-register-firebase-d7462',
    authDomain: 'login-register-firebase-d7462.firebaseapp.com',
    storageBucket: 'login-register-firebase-d7462.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU0r0_noucRYgh9-zRPKHyvtMLeb81A74',
    appId: '1:1048741213886:android:146839c4f0ee68534350ef',
    messagingSenderId: '1048741213886',
    projectId: 'login-register-firebase-d7462',
    storageBucket: 'login-register-firebase-d7462.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSJpFLvKmybbCednJ_WQgdHCNtR0AMAkU',
    appId: '1:1048741213886:ios:56eb9cb52ca9ac6a4350ef',
    messagingSenderId: '1048741213886',
    projectId: 'login-register-firebase-d7462',
    storageBucket: 'login-register-firebase-d7462.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSJpFLvKmybbCednJ_WQgdHCNtR0AMAkU',
    appId: '1:1048741213886:ios:04087457bc752d744350ef',
    messagingSenderId: '1048741213886',
    projectId: 'login-register-firebase-d7462',
    storageBucket: 'login-register-firebase-d7462.appspot.com',
    iosBundleId: 'com.example.newsapp.RunnerTests',
  );
}
