// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Bei6fotQ-nMA1-MlpbXK3XOKG8bYVTU',
    appId: '1:929870998944:web:c86ef8c0dd8fc78c2d48c5',
    messagingSenderId: '929870998944',
    projectId: 'newsapp-b8968',
    authDomain: 'newsapp-b8968.firebaseapp.com',
    storageBucket: 'newsapp-b8968.appspot.com',
    measurementId: 'G-1SSN7GD538',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrxsb3dB-2OR1BeU0VEtLMqcdhywNwfjg',
    appId: '1:929870998944:android:681ac6b6b74839d12d48c5',
    messagingSenderId: '929870998944',
    projectId: 'newsapp-b8968',
    storageBucket: 'newsapp-b8968.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5W9NreGYK46SX_VdfU37MzuR0oGlgLHg',
    appId: '1:929870998944:ios:7fd90434c245200e2d48c5',
    messagingSenderId: '929870998944',
    projectId: 'newsapp-b8968',
    storageBucket: 'newsapp-b8968.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5W9NreGYK46SX_VdfU37MzuR0oGlgLHg',
    appId: '1:929870998944:ios:8dd77387463745fb2d48c5',
    messagingSenderId: '929870998944',
    projectId: 'newsapp-b8968',
    storageBucket: 'newsapp-b8968.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
