name: flutter_medical_demo1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+3
  shared_preferences: ^2.0.6
  path_provider: ^2.0.5
  get: 4.6.6
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  webview_flutter: ^2.0.13

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/
  uses-material-design: true
